print("Welcome to tip calculator")
bill = float(input("what is the total bill? "))
tip = int(input("What percentage of tip would you like to give? "))
nos = int(input("enter the number of people you want to split the bill with: "))
tot_bill = bill+(bill*tip/100)
print(f"Each of you will pay {round(tot_bill/nos,2)} $")